spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: cdraayush@gmail.com
    password: "zecedmeofzxaoijc"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379

jwt:
  secret:
    key: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
  expiry: 1800000

admin:
  name: "aayush"
  password: "aayush"
  email: "caayush96@gmail.com"
  role: "ROLE_ADMIN"
  phone: "9844430402"

thread:
  corePoolSize: 10
  maxPoolSize: 10
  queueCapacity: 100
  threadNamePrefix: "Save-Multiple-Users-thread-pool-"

flags:
  sendEmail: false

emailLogChar:
  maxLength: 255

external:
  property:
    file:
      path: file:/C:/Users/ThinkPad/Documents/Property_File/encryption/src/main/resources/external_application.properties
    encryption:
      key: secret_key